version: '3.8'
services:
  app:
    container_name: request-network-app
    build: .
    command: ["pnpm", "dev"]
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres
    ports:
      - "${API_PORT}:${API_PORT}"

  db:
    container_name: request-network-db
    image: supabase/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data

  
