services:
  app:
    container_name: request-network-app
    build: .
    command: ["sh", "-c", "while ! nc -z db 5432; do sleep 1; done; pnpm db:migrate && pnpm dev"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - MIGRATE=true
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
      - PATH=/usr/src/app/node_modules/.bin:$PATH
    ports:
      - "${API_PORT}:${API_PORT}"

  db:
    container_name: request-network-db
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  
