services:
  app:
    container_name: request-network-app
    build: .
    command: ["sh", "-c", "while ! nc -z db 5432; do sleep 1; done; pnpm db:migrate && pnpm dev"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - MIGRATE=true
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
      - PATH=/usr/src/app/node_modules/.bin:$PATH
    ports:
      - "${API_PORT}:${API_PORT}"

  db:
    container_name: request-network-db
    image: supabase/postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data

  
